### ISSUE TITLE
Sharding of service

### ISSUE THREAD

**Issue by emiliobasualdo** [bmoscon/cryptostore#169]
Hi there. So the idea of this project is to collect market data and some of us want collect data for a couple of months, years, etc.

The service could be sharded by creating various simultaneous docker containers to distribute the load of processing many different symbols and data_types.

What do you think? Would this be a recommended practice? Or would you just create 1 container subscribed to all symbols?

Regards

**Comment by yohplala** [comment]
Hello @emiliobasualdo,
At some point, if you increase the amount of data, when increasing the amount of data, you reach some limits.
From my own experience, when adding data:

 - the 1st limit I reached was RAM of server. Most notably processing of the full orderbook for some much traded pairs (like BTC/USD on Coinbase) require up to 1,8Go of RAM.   => I moved from a 2Go to 4Go server
    The point to notive here is that you don't need many pair. Only order book in delta with BTC/USD on Coinbase will make Cryptostore fails in day of high trading activity (at some point, ht efulle order book is requested and boom)
 
- After solving this, if you add new pairs, new data, the next limit is CPUs (for processign the data while receiving new data...).
I decided to keep same server and increase number of CPUs, from 3 vCPU to 8 vCPU.

- Then if you still increase number of channels / pairs, the next limits are number of max open files (using parquet append) and number of max ports on server (it is related to Linux OS limits mostly, but would also require tweaking / playing with Async'IO.
Also, at this level, so that this scenario is possible, you need a quite good internet connection to continue feeding your server.
Reaching this limit, I stopped playing with a single server, and switched to 4 of them.

- I have basically 3 servers with 4Go RAM + 4 vCPU  for trades + order books over looooot of pairs.
+ 1 basic server 1vCPU, 2Go of RAM for Coingecko & Whale alert for this same looooot of pairs. But because Coingecko and Whale Alert stream few information, it is ok.

Bests

**Comment by emiliobasualdo** [comment]
Thank you very much for the help! I also have a loooot of pairs, so I'll move to the third step directly. 
Regards!
