### ISSUE TITLE
book_depth parameter for Kraken L2 has no effect

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptostore#34]
The `book_depth` parameter in config.yaml for Kraken L2 data has no effect.  So far I've confirmed that the book depth parameter is being read here: https://github.com/bmoscon/cryptostore/blob/3ced53a70671befb49de052796803696e06a38cf/cryptostore/collector.py#L41

My config portion for the Kraken exchange looks like so:

```json
    KRAKEN:
        l2_book:
            symbols: [BTC-USD, ETH-USD, LTC-USD]
            book_delta: false
            book_depth: 1000
```

Loading the data and checking the dataframe shape shows it is only 20 rows per book entry (10 on each of the ask/bid as is the default in cryptostore).  I haven't been able to find where the cryptofeed for Kraken is called within cryptostore, so I'm not sure how to fix it myself.

**Comment by nateGeorge** [comment]
Also, it seems like the book_depth must be nested under l2 or l3, even though it looks like the code only uses one value for book_depth even if both l2 and l3 are present.  If book_depth is not nested under l2, it seemed to give errors.

**Comment by nateGeorge** [comment]
For now the fix is to set `depth=1000` in cryptofeed here: https://github.com/bmoscon/cryptofeed/blob/de7b2750f8d6d0fa85b06f4843595940ab622d8e/cryptofeed/kraken/kraken.py#L24

**Comment by bmoscon** [comment]
book_depth doesnt actually control how many levels an exchange sends you, its used to trim excess levels on the cryptofeed end before the data is sent to redis. I've adjusted kraken to 1000, so this shouldnt be an issue any more. 

Book depth DOES need to be nested under the book (l2/l3) since its exchange specific. you can have deltas on one exchange and use book depth on another (so its exchange specific now as opposed to top level like it used to be).

**Comment by bmoscon** [comment]
@nateGeorge if you still have issues or questions, do let me know

**Comment by nateGeorge** [comment]
Got it, thanks for the clarification.
