### ISSUE TITLE
Timestamps and timezones

### ISSUE THREAD

**Issue by chazzmoney** [bmoscon/cryptostore#69]
Two quick questions -

1. Just want to verify that the timestamps used to generate filenames when saving files is UTC?
2. Is there an easy way to add a date into the folder path of the files being saved?

Thank you!

**Comment by bmoscon** [comment]
yes, all timestamps should be UTC.
to add the date to the path, add it here:

https://github.com/bmoscon/cryptostore/blob/master/cryptostore/data/parquet.py#L70-L71

path = f"{prefix}/{date}/{path}"

where date is whatever date string you create


Since this is a question, I'm going to close this, but feel free to continue to ask questions here, or join the slack and ask them there.

**Comment by chazzmoney** [comment]
Thank you for the fast response - very useful!

One more question for you. In the config, I know that you can set the interval. For example, if we wanted to capture every 60 seconds, we would use the interval '60'. I also could use 'M'. It seems like both of these do the same thing - or does 'M' capture right on the start/end of the minute?

The reason I ask is because if I use the {date} piece, I want that folder to contain all the data that happened on that date, and nothing outside that date. Does that make sense?
