### ISSUE TITLE
Recent data backfill issue

### ISSUE THREAD

**Issue by rbdm-qnt** [bmoscon/cryptostore#74]
Hi! 
I've turned on the backfill option on the config (I'm backfilling BitMEX tick data), the backfill works fine for historical data (from 2016 to 2019), but it won't backfilled the hours where I had my computer turned off in the last week. I have 8 hours holes in the database for most days from March 25th 2020 to today. Why could that be? 

Thanks in advance!

**Comment by bmoscon** [comment]
this is because its not currently designed to fill missing data, it will fill from the most oldest data back in time. If you turn it off for 3 days and then turn it back on, it will not fill in those gaps if there is data more recent than that. I'm working on a new backfill that will correct this, but its a complete rewrite of backfill so its not a small task.

**Comment by rbdm-qnt** [comment]
I understand, good to know. Would be amazing to be able to do this automatically! Thanks for you hard work, looking forward for the next update
